{
    "branches": [ "main" ],
    "plugins": [
        "@semantic-release/github",
        "@semantic-release/release-notes-generator", 
        "@semantic-release/commit-analyzer",
        ["@semantic-release/changelog", {
            "changelogFile": "Assets/CHANGELOG.md",
        }],
        ["@semantic-release/npm", {
            "npmPublish": false,
            "pkgRoot": "Assets/Mirror"
        }],
        ["@semantic-release/git", {
            "assets": ["Assets/package.json", "Assets/CHANGELOG.md"],
            "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
        }],
    ]
}
